GMAIL_USERNAME: "thiensangkdtt@gmail.com"
GMAIL_PASSWORD: "1970minh"
GMAIL_PORT: "587"
GMAIL_DOMAIN: "localhost:3000"
GMAIL_ADDRESS: "smtp.gmail.com"
HOST: "localhost:3000"
GMAIL_DEFAULT: "thiensangkdtt@gmail.com"
AUTH_SECRET: "\f\xF4g\xDE\x04\xFD\x9B!\x15\xEE\xA1\xC2[\xF5\x8E\\\xD85\xEB\x85\xA7\xBD\xD9\xBB~\x179-\x84\x06D\x15"
