default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: utf8
  username: root
  password: "minhthong511"


development:
  <<: *default
  database: blog

test:
  <<: *default
  database: blog

production:
  <<: *default
  # database: db/production.mysql2
